#!/bin/bash

./main --year 2007 --format state --file data/occ_2007/state_May2007_dl.xls
./main --year 2007 --format metro --file data/occ_2007/aMSA_May2007_dl.xls
./main --year 2007 --format metro --file data/occ_2007/MSA_May2007_dl_1.xls
./main --year 2007 --format metro --file data/occ_2007/MSA_May2007_dl_2.xls
./main --year 2007 --format metro --file data/occ_2007/MSA_May2007_dl_3.xls
./main --year 2007 --format metro --file data/occ_2007/BOS_May2007_dl.xls

