#!/bin/bash

./main --year 2008 --format state --file data/occ_2008/state__M2008_dl.xls
./main --year 2008 --format metro --file data/occ_2008/aMSA__M2008_dl.xls
./main --year 2008 --format metro --file data/occ_2008/MSA__M2008_dl_1.xls
./main --year 2008 --format metro --file data/occ_2008/MSA_M2008_dl_2.xls
./main --year 2008 --format metro --file data/occ_2008/MSA_M2008_dl_3.xls
./main --year 2008 --format metro --file data/occ_2008/BOS__M2008_dl.xls

